---

- hosts: all 
  become: true
  tasks: 
  - name: install updates (Ubuntu) 
    apt: 
       upgrade: dist
       update_cache: yes 
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:
  - name: install apache2 package & php support
    apt:
      name: 
       - apache2
       - libapache2-mod-php
      state: latest

  - name: copy default html file
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_server
  become: true
  tasks:
  - name: install maria db
    apt:
      name:
        - mariadb-server
      state: latest

